cc_library(
    name = "gba",
    hdrs = [
        "defines.h",
        "flash_internal.h",
        "gba.h",
        "io_reg.h",
        "isagbprint.h",
        "macro.h",
        "multiboot.h",
        "syscall.h",
        "types.h",
    ],
    visibility = ["//visibility:public"],
)
