cc_library(
    name = "main",
    srcs = ["main.c"],
    # Make available to test
    hdrs = ["main.c"],
    visibility = ["//testing/unit:__pkg__"],
    deps = [
        "//include",
        "//include/constants",
        "//include/gba",
    ],
)
